export interface Socio {
  name: string;
  email: string;
  cv: string;
}

export const sociosData: Socio[] = [
  {"name": "Adriana Lourenço Lopes", "email": "adrianalourencolopes@gmail.com", "cv": "http://lattes.cnpq.br/9686139344430086"},
  {"name": "Adriana Grando", "email": "adrgrando@gmail.com", "cv": "http://lattes.cnpq.br/6655526661447047"},
  {"name": "Adriana de Fátima Fontes", "email": "adrianafontes.psico@gmail.com", "cv": ""},
  {"name": "Adriane Gomes Queiroz", "email": "adriane.queiroz.g@gmail.com", "cv": ""},
  {"name": "Adriano Rodrigues Dos Santos", "email": "adrianorodrigues6@hotmail.com", "cv": ""},
  {"name": "Adrieli Gonçalves Dos Santos", "email": "agsantos01@outlook.com", "cv": ""},
  {"name": "Alan Souza Aranha", "email": "alansaranha@gmail.com", "cv": "http://lattes.cnpq.br/3642620826614727"},
  {"name": "Alana Dos Anjos Moreira", "email": "alanamoreirapsi@gmail.com", "cv": ""},
  {"name": "Alceu Martins Filho", "email": "alceu.ms@gmail.com", "cv": "http://lattes.cnpq.br/9935669683108405"},
  {"name": "Alcione Sá", "email": "alcioneferreira.psi@gmail.com", "cv": "http://lattes.cnpq.br/2039235133640472"},
  {"name": "Aldeíne Martins", "email": "psi.deinymartins@gmail.com", "cv": ""},
  {"name": "Alessandra Avanzi", "email": "aleavanzi7@gmail.com", "cv": ""},
  {"name": "Alessandra Pimenta de Souza", "email": "alepossani@icloud.com", "cv": ""},
  {"name": "Alessandra Honorato Benfica Franco", "email": "alessandra.fls.pdg@gmail.com", "cv": "https://lattes.cnpq.br/4264580994487086"},
  {"name": "Alessandra Bizeli Oliveira Sartori", "email": "alessandra.sabiamente@gmail.com", "cv": ""},
  {"name": "Alexandra Cristina Souza Gomes de Paula", "email": "psicologiale@hotmail.com", "cv": ""},
  {"name": "Alexandre Xavier", "email": "alexavier_s@hotmail.com", "cv": ""},
  {"name": "Alexandre Aguiar Victuri", "email": "alevicturi@gmail.com", "cv": "https://lattes.cnpq.br/3410876309159688"},
  {"name": "Alexia Oshiro", "email": "alexiapsico98@gmail.com", "cv": ""},
  {"name": "Alice Maciel Ferreira Monteiro", "email": "alicef40@gmail.com", "cv": ""},
  {"name": "Aline Baldo", "email": "aline_baldo@hotmail.com", "cv": "https://lattes.cnpq.br/1643546172897643"},
  {"name": "Aline Kabbaz", "email": "aline.bfkabbaz@gmail.com", "cv": "https://lattes.cnpq.br/1547309656020640"},
  {"name": "Aline da Silva Rodrigues Marques", "email": "psi.alinesrodrigues@gmail.com", "cv": "http://lattes.cnpq.br/7005398011532677"},
  {"name": "Aline Banganha Prato", "email": "alineprato@hotmail.com", "cv": ""},
  {"name": "Aline França", "email": "psicologaalinefranca@gmail.com", "cv": ""},
  {"name": "Aline Daniela Gomes da Silva Vieira", "email": "ad.vieira@usp.br", "cv": "http://lattes.cnpq.br/2556824378856957"},
  {"name": "Amanda de Melo", "email": "amandav.meloo@gmail.com", "cv": "http://lattes.cnpq.br/2161469271053940"},
  {"name": "Amanda Raña Ferreira", "email": "amanda.rana@gmail.com", "cv": ""},
  {"name": "Amanda Oliveira de Morais de Morais", "email": "amandaomorais@gmail.com", "cv": "http://lattes.cnpq.br/2915880924460589"},
  {"name": "Amilcar Rodrigues Fonseca Júnior", "email": "ajrpsico@yahoo.com.br", "cv": "http://lattes.cnpq.br/4367734116952280"},
  {"name": "Amona Lima", "email": "amona_priscila@yahoo.com.br", "cv": "http://lattes.cnpq.br/0614921738135666"},
  {"name": "Ana Perriello", "email": "espacosensi@gmail.com", "cv": ""},
  {"name": "Ana Karina Leme Arantes", "email": "ana.arantes@gmail.com", "cv": "http://lattes.cnpq.br/1785475312488456"},
  {"name": "Ana Alice Reis Pieretti", "email": "anaalicereisp@gmail.com", "cv": ""},
  {"name": "Ana Beatriz Tolentino da Silva", "email": "anasi@ufcspa.edu.br", "cv": ""},
  {"name": "Ana Beatriz de Deus", "email": "abeatrizdedeus@gmail.com", "cv": "https://lattes.cnpq.br/6424014663824574"},
  {"name": "Ana Beatriz Briones Mantovani", "email": "aninhabrionesm@gmail.com", "cv": ""},
  {"name": "Ana Camila Marcelo", "email": "anacamilamarcelo@gmail.com", "cv": ""},
  {"name": "Ana Carolina Pereira Alves", "email": "carol.alves@entremeioic.com.br", "cv": "http://lattes.cnpq.br/7330382621797345"},
  {"name": "Ana Carolina Cainé Canassa", "email": "psicoaccanassa@gmail.com", "cv": "http://lattes.cnpq.br/5505210106808379"},
  {"name": "Ana Cláudia de Oliveira Costa de Souza", "email": "anaclaudiaoc@gmail.com", "cv": ""},
  {"name": "Ana Elisa Coelho", "email": "anaelisavcoelho@gmail.com", "cv": "http://lattes.cnpq.br/4892425777453322"},
  {"name": "Ana Elisa Quintal", "email": "anaelisaquintal@gmail.com", "cv": ""},
  {"name": "Ana Heloisa Beltram de Oliveira", "email": "anabeltram@outlook.com", "cv": "https://lattes.cnpq.br/6681531124195316"},
  {"name": "Ana Julia Lima Souza Lima Souza", "email": "anajulialimasouzaa@gmail.com", "cv": ""},
  {"name": "Ana Luiza Vicente Ambrozin", "email": "psianaluizaambrozin@gmail.com", "cv": ""},
  {"name": "Ana Luiza Costa Roncati", "email": "analuizaroncati@gmail.com", "cv": ""},
  {"name": "Ana Paula Bernardes", "email": "anapsicoinf@gmail.com", "cv": ""},
  {"name": "Ana Pilar Navarro de Godoy Marin", "email": "anapilar.psi@gmail.com", "cv": ""},
  {"name": "Ana Priscila Martelozo", "email": "primartelozo@hotmail.com", "cv": ""},
  {"name": "Ana Vitória Sanches de Camargo", "email": "psi.anasanches@gmail.com", "cv": "http://lattes.cnpq.br/8345455345416287"}
];
